### ISSUE TITLE
Canary deployment error

### ISSUE THREAD

**Issue by gbaeke** [Azure/k8s-deploy#101]
Repro steps:
- Version 0.0.1 deployment without canary (5 replicas; in namespace meshed with linkerd)
- Version 0.0.2 deployment with canary using the following YAML:

- uses: azure/k8s-deploy@v1
   with:
     namespace: go-template
     manifests: ${{ steps.bake.outputs.manifestsBundle }}
     images: |
       ghcr.io/USER/IMG:${{ env.IMAGE_TAG }}
     strategy: canary
     percentage: 20
     traffic-split-method: smi
     baseline-and-canary-replicas: 1

Current behaviour:
- Canary deployment of 0.0.2 fails with the following error: StableSpecSelectorNotExist : deploymentname

Expected behaviour:
- Canary deployment succeeds with SMI TrafficSplit

Extra information:
- canary deployment succeeds without SMI
- namespace of the deployment has the following linkerd annotation - linkerd.io/inject: enabled
- also tried without baseline-and-canary-replicas - same issue

**Comment by ds-ms** [comment]
@gbaeke have you tried using one of our latest versions? `v1.4` or `v1.3` maybe?

**Comment by gbaeke** [comment]
@ds-ms I tried both 1.3 and 1.4 without luck

**Comment by lfraile** [comment]
Any news on this topic? I'm running the same issue :(

**Comment by gbaeke** [comment]
Hi,

I documented my experience in this blog post: https://blog.baeke.info/2021/01/11/kubernetes-canary-deployments-with-github-actions/. Following the steps in the post, I did not have the issue.

**Comment by lfraile** [comment]
Great, thanks @gbaeke will take a look

**Comment by lfraile** [comment]
So it worked @gbaeke , it seems, as far as I understand, you have to deploy the first time using this tasks from scratch, as if a previous deployment already exists get stuck

**Comment by ds-ms** [comment]
>you have to deploy the first time using this tasks from scratch, as if a previous deployment already exists get stuck

That is correct. We took this decision consciously to avoid breaking existing setups accidentally.
