### ISSUE TITLE
azure/k8s-actions/k8s-deploy@v1 doesn't find the source

### ISSUE THREAD

**Issue by serkanersanli** [Azure/k8s-deploy#11]
As the new version tries to download the source from here : https://api.github.com/repos/azure/k8s-actions/tarball/v1

it raises the below error : 
Download action repository 'azure/k8s-actions@v1'
##[warning]Failed to download action 'https://api.github.com/repos/azure/k8s-actions/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 27.052 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/azure/k8s-actions/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 12.885 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).

I am using the github actions workflow and when I use azure/k8s-actions/k8s-deploy@v1 instead of azure/k8s-actions/k8s-deploy@master job fails at the beginning as there is no reference resource in the destination

**Comment by ronbeilinson** [comment]
Has this been resolved?
