### ISSUE TITLE
Traceability Schema

### ISSUE THREAD

**Issue by ammohant** [Azure/k8s-deploy#114]
Traceability Schema

Abstract
Traceability  involves ability to track the source for issue, code, commit, artifact, workflow, and the user from the package deployed on the resource, through documented records.  This document proposes the traceability schema which captures the traceability data for any deployment which can be used by any "CI/CD" providers and cloud providers to organize the traceability data and  consume it in various forms. 

Format:
  The schema organizes the information in the following way 

- Categorization of various sections :

     - How did it get deployed ?
        Captures the commit and workflow details was the trigger and resulted in the deployment of a generated
        artifact to a resource

    - What was deployed ?
       Captures the artifacts’ details that has been deployed

   - Where did it get deployed ?
      Captures the target resource where the deployment has happened.

       The “How” and “Where” part can come from various providers which the schema factors in by having a provision to have
        any new source “type/provider” to use the schema to generate the traceability data or a cloud provider to deploy the 
        data onto its respective cloud. This definition of the schema makes it agnostic to both cloud providers
        (Azure, AWS, GCP ,Kusto) as well as  source control providers (GitHub, ADO, Bitbucket). 

- Representation of a specific section:
    Data is organized into the following in each of the section/categorizes within the traceability data -
    - "Category of data"
        - "Provider of the data"
            -  Associated properties specific to the provider
                - The data is organized into multiple subsections/objects as appropriate. 
                - The data is organized into objects factoring in the hierarchy. Will restrict to a depth 
                  of two. Building the tree is outside the scope and goal of this schema.
                - The data  in the property bag does not follow the paradigm of include all rather follows the 
                   paradigm of include relevant/important  data which will help consumer to trace deployment
                   of an artifact on a resource and the trace the change in resource that resulted due to the act 
                   of deployment
                -  We will continuously review the deployment traceability needs on various resources and 
                    artifacts across cloud types, involve the community for feedback and review the property
                    bag schema accordingly.

```
{
   "id": " " /* The unique identifier of the traceability object. The intent is for this to be unique, 
                     filtering on this is not an ask as yet */

   "timestamp" : " " /* The timestamp of the creation of traceability object */  

   "schema-version": " " /* Schema version of the traceability object */

   "data":{  /* This section captures all the traceability data split into three subsections of devops, artifacts 
                     and target resource */

       "devops": {  /* This section captures the information related to the code hosting or CI/CD platform. */

           "type": " " /* This is the provider/type of the CI/CD or code hosting platform. GitHub, ADO, BB Pipelines etc. 
                              can be the possible types along with many others. */

           "properties" :{ 
                /*  The contents of this property bag would depend on the constructs and entities pertaining
                    to the type of CI/CD provider specified in the above field.  This will broadly encompass
                    information on commits, pipelines, workflow runs, Issues etc. 
               */ 
           }
       },

       "artifact": { /* This section captures the information of the associated artifacts */

           "type" : " " /* This is the type of artifact. It can be a build artifact or an Image artifact. 
                                 For ex. Docker file, Manifest, container Image, JAR etc.*/

           "properties":{
                        /* This property bag captures detailed information of the source and other properties 
                            of the associated artifact.
                            A broad classification of the usage of artifact type will be as follows - 
                                       For target resource as the Image registery the artifact section would contain the 
                                       build artifacts that were used to produce the Image.
                                       For target resource as the AKS/WebApp/DB the artifact section would contain the 
                                       Information on the source of the Image and other data associate to Image that is
                                       deployed on the resource. 
                           For example, 
                           Docker file - This property bag would contain associated information like repository, path, 
                                         commit associated with the same 
                           Image       - This property bag would contain associated information like repository, registry, 
                                          Image SHA etc. associated with the Image.
                      */
           },
       },
       "target resource":{ 
                         /* This is target resource to which the deployment has happened. It would typically be the 
                            cloud provider like ACR, Azure, AWS and GCP.  The definition is the prerogative of the cloud
                            provider who is consuming this traceability object */

           "type": " ", /* This will be the cloud provider type like Azure,AWS, GCP etc. Can also extend to any other
                                 traceability stores like Kusto, AI and others */

             "StartTimestamp":"" /* Start time stamp of the deployment */

             "EndTimestamp":""  /* End time stamp of the deployment */

               "properties":{
                               /*  */
                   },
               }
       }  
   } 

```

**Comment by kmkumaran** [comment]
> The data is organized into objects factoring in the hierarchy

Should we be explicit about the depth in hierarchy. Call out that that we will limit to immediate parent or to the immediate child and not capture hierarchy beyond that. Building the tree is outside the scope and goal of this schema.

>The data in the property bag does not follow the paradigm of include all rather follows the
paradigm of include relevant/important data which will help the consumer use the published
in a more effective and efficient manner

Should we rephrase to "... which will help consumer to trace deployment of an artifact on a resource and the trace the change in resource that resulted due to the act of deployment"

**Comment by kmkumaran** [comment]
Instead of forking this conversation in multiple issues, can we use https://github.com/Azure/k8s-deploy/issues/111 for the current topic as well?

**Comment by ammohant** [comment]
@kmkumaran . Ok I updated the comments. Will move to #111

**Comment by kmkumaran** [comment]
@ammohant - Do we need this issue or can this be closed?

**Comment by ammohant** [comment]
Yes, will close this one.
