### ISSUE TITLE
ARM and other arch's support

### ISSUE THREAD

**Issue by gtrubach** [Azure/k8s-deploy#115]
Hello,

I see in code that kubectl arch is hard-coded to amd64. Is it possible to make it download kubectl depending on agent arch? As I understand `os.arch()` should return correct architecture and if it used, correct kubectl will be downloaded.

**Comment by azooinmyluggage** [comment]
@ds-ms Any particular reason why we stopped at amd64?

**Comment by azooinmyluggage** [comment]
Any other action which may have the same problem?

**Comment by gtrubach** [comment]
I saw several, and all of them have hard-coded amd64 arch for kubectl download. For instance:
* https://github.com/Azure/setup-kubectl
* https://github.com/Azure/k8s-lint

**Comment by ds-ms** [comment]
@azooinmyluggage @gtrubach I believe we hard-coded them to support `hosted runners` in the beginning. We can start supporting this, with the `Self hosted runners` made GA.

@gtrubach would you be willing to raise a PR for the same? 😃

**Comment by gtrubach** [comment]
@ds-ms Sorry for long silence, will try to create a PR this weekend.
