### ISSUE TITLE
deploying to micro k8s

### ISSUE THREAD

**Issue by geoff-marine** [Azure/k8s-deploy#118]
I'm trying to deploy to a single cluster micro k8s instance.  I can run the various actions needed in my pipeline and I don't get any errors but the deployment doesn't happen on my cluster.  When I run kubectl apply against my deployment manifest, it does deploy to the cluster.  My pipeline code:

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: build container and deploy it
    steps:
      - uses: actions/checkout@master

      - name: dockerhub login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push container to dockerhub      
        run: |
          docker build . -t <my docker hub>/k8sdemo:${{ github.sha }}
          docker push <my docker hub>/k8sdemo:${{ github.sha }}

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' 
        id: install 

      - uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MYKUBECONFIG }}
          context: microk8s
        id: setcontext

      - uses: Azure/k8s-deploy@v1.3
        with:
          namespace: default
          images: '<my docker hub>/k8sdemo:${{ github.sha }}'
          manifests: |
            deployment.yaml 
          kubectl-version: 'v1.20.0'   
        id: deploy

**Comment by geoff-marine** [comment]
Anything?

**Comment by ds-ms** [comment]
@geoff-marine internally the action also runs `kubectl` commands only. Would you be comfortable sharing the debug logs of your run where it couldn't deploy?

**Comment by geoff-marine** [comment]
yep - here are the logs of the deploy step.  It reports success but nothing gets deployed to my cluster (have double checked that my kubeconfig is the right one in my env secrets)

Run Azure/k8s-deploy@v1.3
  with:
    namespace: default
    images: ***/k8sdemo:223112d47ba533f4d8757f0e2849d6e8912c7d07
    manifests: deployment.yaml 
  
    kubectl-version: v1.20.0
    strategy: none
    route-method: service
    version-switch-buffer: 0
    traffic-split-method: pod
    baseline-and-canary-replicas: 0
    percentage: 0
    action: deploy
    force: false
    token: ***
  env:
    DOCKER_CONFIG: /home/runner/work/_temp/docker_login_1614684625599
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_1614684633502
strategy:  none
/opt/hostedtoolcache/kubectl/1.20.0/x64 apply -f /tmp/deployment.yaml --namespace default
/opt/hostedtoolcache/kubectl/1.20.0/x64 rollout status Deployment/k8sdemo --namespace default
/opt/hostedtoolcache/kubectl/1.20.0/x64 get namespace/default -o json --namespace default
/opt/hostedtoolcache/kubectl/1.20.0/x64 annotate namespace default githubWorkflow_5c9c36307bf3b5f23f989a1c5b92b378={"run":"613869784","repository":"geoff-marine/hello-world-docker-action","workflow":".github/workflows/main.yml","workflowFileName":"main.yml","jobName":"hello_world_job","createdBy":"geoff-marine","runUri":"https://github.com/geoff-marine/hello-world-docker-action/actions/runs/613869784","commit":"223112d47ba533f4d8757f0e2849d6e8912c7d07","branch":"refs/heads/main","deployTimestamp":1614684634110,"dockerfilePaths":{"***/k8sdemo:223112d47ba533f4d8757f0e2849d6e8912c7d07":""},"manifestsPaths":["https://github.com/geoff-marine/hello-world-docker-action/blob/223112d47ba533f4d8757f0e2849d6e8912c7d07/deployment.yaml"],"helmChartPaths":[],"provider":"GitHub"} --overwrite --namespace default
/opt/hostedtoolcache/kubectl/1.20.0/x64 annotate -f /tmp/deployment.yaml githubWorkflow_5c9c36307bf3b5f23f989a1c5b92b378={"run":"613869784","repository":"geoff-marine/hello-world-docker-action","workflow":".github/workflows/main.yml","workflowFileName":"main.yml","jobName":"hello_world_job","createdBy":"geoff-marine","runUri":"https://github.com/geoff-marine/hello-world-docker-action/actions/runs/613869784","commit":"223112d47ba533f4d8757f0e2849d6e8912c7d07","branch":"refs/heads/main","deployTimestamp":1614684634110,"dockerfilePaths":{"***/k8sdemo:223112d47ba533f4d8757f0e2849d6e8912c7d07":""},"manifestsPaths":["https://github.com/geoff-marine/hello-world-docker-action/blob/223112d47ba533f4d8757f0e2849d6e8912c7d07/deployment.yaml"],"helmChartPaths":[],"provider":"GitHub"} --overwrite --namespace default
/opt/hostedtoolcache/kubectl/1.20.0/x64 label -f /tmp/deployment.yaml workflowFriendlyName=main.yml workflow=githubWorkflow_5c9c36307bf3b5f23f989a1c5b92b378 --overwrite --namespace default

**Comment by geoff-marine** [comment]
I can zip up the rest of the logs if that would help too?

**Comment by ds-ms** [comment]
The zip should be helpful 😄

**Comment by geoff-marine** [comment]
[logs_47.zip](https://github.com/Azure/k8s-deploy/files/6108337/logs_47.zip)

Cool - here you go.  Hopefully I've just been doing something stupid...

**Comment by geoff-marine** [comment]
Figured it out - issue was on my side, firewall was not allowing github access to my cluster.  I only realized this once I manually ran kubectl inside an action and got an error saying kubectl couldn't reach the server.  Totally my mistake - feedback I would give though is that the azure/k8s-deploy action didn't give an error and perhaps its should.
