### ISSUE TITLE
blue-green does not work with latest ingress api version

### ISSUE THREAD

**Issue by xmclark** [Azure/k8s-deploy#143]
Repro steps:
- Create a blue-green deployment pipeline configured for ingress strategy. 
- Add an ingress yaml that uses the latest api version 'networking.k8s.io/v1' 

Current behavior:
- During deployment, a green ingress is not created
- During the promotion step, the ingress is not updated
- the green deployment is destroyed as expected but the traffic never changes to the new pods

Expected behavior:
- I expect a new ingress and traffic to change to new pods

**Comment by koushdey** [comment]
@xmclark You closed the PR #142. Are you planning to close the issue?

**Comment by xmclark** [comment]
Hi @koushdey I am not. Someone else can take the work if they like.

**Comment by OliverMKing** [comment]
Hello! We will look into this.

**Comment by OliverMKing** [comment]
Need to make a release for this. The code is done :)
