### ISSUE TITLE
Add the ability to turn off annotations for one or more resource types

### ISSUE THREAD

**Issue by cdeneen** [Azure/k8s-deploy#149]
We have some shared namespaces and the user provided the action doesn't have permissions to modify the namespace. This causes each job run to have the warning

`"Error from server (Forbidden): namespaces <namespace> is forbidden: User <user> cannot patch resource "namespaces" in API group "" "`

It would great if I could provide a list of Kubernetes resource types (ex "namespaces") to skip being annotated.

**Comment by jaredready** [comment]
Getting some guidance on _why_ this Action needs to annotate namespaces would be helpful. Our IaC will overwrite these annotations and we're unsure whether it's safe to do so or not.

**Comment by roehrijn** [comment]
@jaredready, I think the annotations are only for convenience to add some metadata about the GitHub workflow executing the deployment.

I recently tried to migrate from v1.5 to v3.0 and in the latter version this error about annotating the namespace is treated as a real error which causes the task to fail, whereas in v1.5 it was treated as a warning. This currently blocks me from using newer versions and I also would highly appreciate to have this annotation aspect being configurable.
