### ISSUE TITLE
Add support for TrafficSplit annotations

### ISSUE THREAD

**Issue by tillig** [Azure/k8s-deploy#151]
When SMI traffic handling is selected, the `TrafficSplit` that gets generated (both for [blue/green](https://github.com/Azure/k8s-deploy/blob/33608d18f7cac6ef9e3a4b2831622ab560909e88/src/utilities/strategy-helpers/smi-blue-green-helper.ts#L102) and [canary](https://github.com/Azure/k8s-deploy/blob/33608d18f7cac6ef9e3a4b2831622ab560909e88/src/utilities/strategy-helpers/smi-canary-deployment-helper.ts#L189) is pretty hard-coded with only weights and service names.

At least with Istio, this will only work for services accessed from within the cluster. To get this working with ingress traffic, the Istio `VirtualService` needs to have a `gateway` attached.

The Istio SMI adapter [has support for setting this through annotations](https://github.com/servicemeshinterface/smi-adapter-istio/blob/540c15f49cd800ef32f49751aa89b4464a321203/pkg/controller/trafficsplit/trafficsplit_controller.go#L192) but there's no way to add annotations to the generated `TrafficSplit`.

**It would be cool to be able to add annotations to the `TrafficSplit` to support cases like this.** It could be a key/value list parameter to the task and just copied into the `TrafficSplit` when it's generated. If none are present, you get the same thing you get now. (Admittedly, I'm kind of new to GitHub Actions and I'm unclear if it'd need to be a multiline string or if you can have `object` style parameters like Azure DevOps. Either way is fine.)

[Corresponding issue filed for Azure DevOps `KubernetesManifest` task.](https://github.com/microsoft/azure-pipelines-tasks/issues/15272)

**Comment by tillig** [comment]
14 days idle seems a little short for feature suggestions. It'd still be good to have this. I haven't moved to GitHub Actions yet but we're targeting that move in my organization for Q1 2022. In the meantime I've forked the baked-in AzDO task and have to own that for the next several months. I can get a PR in for this but it'd be nice to hear from the team if it's interesting before I invest the time.

**Comment by tillig** [comment]
It would be nice to hear if this is interesting to the team before doing to work to create a pull request.

**Comment by OliverMKing** [comment]
Hi @tillig. We'd love this feature. Please feel free to create a PR.

**Comment by tillig** [comment]
Awesome. We're still in the process of getting our GitHub Enterprise system underway. That'll be my test bed for verifying my changes before submitting the PR since I don't really have any other system with everything wired up. However, I do plan on getting a PR in here so I'll keep this open while I work on it. Thanks!

**Comment by OliverMKing** [comment]
@Vidya2606 is actively working on this.

**Comment by OliverMKing** [comment]
@tillig do you have any links to documentation talking about using the annotation for Istio SMI adapter? I can see it in the code but I'm struggling to find docs.

**Comment by OliverMKing** [comment]
This feature was added to the latest version :). You can use the `traffic-split-annotations` input. Thanks!
