### ISSUE TITLE
Kubectl wrong architecture being downloading 

### ISSUE THREAD

**Issue by yenser** [Azure/k8s-deploy#153]
The amd64 version of kubectl gets installed instead of the arm64 version when running on a self-hosted runner.

![image](https://user-images.githubusercontent.com/22648844/137203000-e40afb05-0651-47bd-914c-efecfbb496f6.png)

Repro steps:
- Self-hosted action controller running on Raspberry Pi 4 Model B
- Ubuntu 21.04
- Running `uname -m` in the same action will return with the value `aarch64` to validate the systems architecture.

Current behavior:
- amd64 version of kubectl gets installed instead of the arm64.
- kubectl execution errors
![image](https://user-images.githubusercontent.com/22648844/137203386-f49e6120-bf3a-4973-b1ad-71839e6a0670.png)

Expected behavior:
- arm64 version of kubectl should be installed on an arm64 architecture.
- No execution error when running kubectl

**Comment by OliverMKing** [comment]
The latest version of this action no longer downloads Kubectl itself. Use [Azure/setup-kubectl](https://github.com/Azure/setup-kubectl) to install the appropriate version.
