### ISSUE TITLE
How  to specify the previous workload to promote/reject.

### ISSUE THREAD

**Issue by MNF** [Azure/k8s-deploy#154]
In the section “[To promote/reject the green workload created by the above snippet, the following YAML snippet could be used:](https://github.com/Azure/k8s-deploy#to-promotereject-the-green-workload-created-by-the-above-snippet-the-following-yaml-snippet-could-be-used)” It  is not clear how I can specify the previous workload to promote/reject. Could  you please answer and elaborate in the Readme.

Is ${{ event.run_id }} system generated value or something that developer need to specify.
Should developer somehow ensure that ${{ event.run_id }} for create and corresponding reject yaml spec?

Another minor typo in https://github.com/Azure/k8s-deploy#to-promotereject-the-canary-created-by-the-above-snippet-the-following-yaml-snippet-could-be-used-1
In line `action: reject #substitute reject if you want to reject`
Should be `action: promote`

**Comment by michael-freidgeim-webjet** [comment]
What “idle”label means? Should I do something to attract attention to the question?

**Comment by OliverMKing** [comment]
You just need the manifests passed to both actions to be the same. event.run_id is generated and it's a way to specify a specific tag with artifact substitution. 

If artifact substitution is used, the tag needs to be the same when promoting / rejecting.
