### ISSUE TITLE
Canary deployment not working with OSM

### ISSUE THREAD

**Issue by jjindrich** [Azure/k8s-deploy#155]
I need to configure canary deployment with OSM (SMI compatible) https://github.com/openservicemesh/osm
When I configure this task:
`    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        namespace: 'jjweb'
        strategy: canary
        traffic-split-method: smi
        action: deploy #deploy is the default; we will later use this to promote/reject
        percentage: 20
        baseline-and-canary-replicas: 1`

Getting this error, seems some converting problem:
`error: error validating "/tmp/TrafficSplit_jjwebcore_1635240648649": error validating data: [ValidationError(TrafficSplit.spec.backends[0].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[1].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[2].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number"]; if you choose to ignore these errors, turn validation off with --validate=false
Error: Error: error: error validating "/tmp/TrafficSplit_jjwebcore_1635240648649": error validating data: [ValidationError(TrafficSplit.spec.backends[0].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[1].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number", ValidationError(TrafficSplit.spec.backends[2].weight): invalid type for io.smi-spec.split.v1alpha2.TrafficSplit.spec.backends.weight: got "string", expected "number"]; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by jjindrich** [comment]
@shigupt202 pls can you help me how to fix this issue ?

**Comment by qpetraroia** [comment]
Adding @OliverMKing

**Comment by OliverMKing** [comment]
Created a new release v1.5 fixing this.
