### ISSUE TITLE
Remove tag v1.4

### ISSUE THREAD

**Issue by SamMousa** [Azure/k8s-deploy#156]
There is a tag v1.4 in the repo that doesn't have a release. Also it was created before the 1.3 tag..

I think the tag should be removed, or, if you don't want to break clients, release a new version v1.5 so that people will get the correct version when they just look for the "biggest tag"

**Comment by SamMousa** [comment]
It should not be idle... Bump

**Comment by SamMousa** [comment]
Bump

**Comment by SamMousa** [comment]
Bump... is someone even looking at issues in this repo?

**Comment by SamMousa** [comment]
@davidgamero sorry for being rude and just pinging you (because you've been committing to this repo recently).
Could you please get someone to look at this issue?
I'm always happy to implement PRs where I can, but in this case this is something a repository admin has to do.

**Comment by davidgamero** [comment]
Thank you for bringing this up. I'll take a look

**Comment by davidgamero** [comment]
Looks like there was a prerelease for v1.4, but v1.5 should be live now
