### ISSUE TITLE
Strategy "none" emits warning

### ISSUE THREAD

**Issue by artlogic** [Azure/k8s-deploy#174]
Choosing none as a strategy (which according to the docs is valid) leads to the following warning being emitted: `Deployment strategy is not recognized.` - despite things working as you would expect.

I think two minor changes would make this clearer:
1. Don't emit a warning when a strategy of `none` is selected.
2. Clarify the warning so that it's obvious that no deployment strategy is being used, for example: `Deployment strategy is not recognized, defaulting to no deployment strategy.`

Thanks!

**Comment by OliverMKing** [comment]
@davidgamero is working on this now by renaming and making strategy required. "None" and "no strategy" isn't an accurate description of what's happening when a strategy isn't chosen. It basically fully deploys resources.

**Comment by davidgamero** [comment]
this should be rolled out in the newest v4 release. feel free to re-open if the issue persists
