### ISSUE TITLE
Artifact Substitution is not working

### ISSUE THREAD

**Issue by SaiNageswarS** [Azure/k8s-deploy#176]
I'm pushing docker image with a certain tag in action workflow. While deploying I would like the action workflow to substitute the tag in deployment.yml.

Although readme says that action supports artifact substitution, it doesn't explain how. Kindly share the documentation for the same.

Thanks

**Comment by OliverMKing** [comment]
This is documented under the images part of the [inputs section](https://github.com/Azure/k8s-deploy#action-inputs). I'll look into improving the documentation as well.
