### ISSUE TITLE
Update examples in README to reflect the latest state

### ISSUE THREAD

**Issue by jannaspam** [Azure/k8s-deploy#186]
Looks like `kubectl-version` input was removed in #165 but [the Basic Deployment example]( https://github.com/Azure/k8s-deploy#basic-deployment-without-any-deployment-strategy) still has it. Would be good to clean it up.

**Comment by OliverMKing** [comment]
Good catch! Thanks!

**Comment by OliverMKing** [comment]
It's been removed from the docs.
