### ISSUE TITLE
rolling update error using action Azure/k8s-deploy@v1 - map: map[] does not contain declared merge key: name

### ISSUE THREAD

**Issue by ronbeilinson** [Azure/k8s-deploy#20]
When using the action azure/k8s-actions/k8s-deploy@master rolling deployment works ok, but when we try changing to the latest action (Azure/k8s-deploy@v1) we get the following error. 

<img width="1309" alt="terminal-output" src="https://user-images.githubusercontent.com/14821538/74467316-d37c7080-4e66-11ea-8ab1-228dd313da80.png">
<img width="714" alt="deployment yml screenshot" src="https://user-images.githubusercontent.com/14821538/74467328-d8d9bb00-4e66-11ea-9627-30f6315096b3.png">

Please let me know how to proceed and if this is a known issue.

Thanks!

**Comment by anajavi** [comment]
I am experiencing the same problem. I guess it is the same problem as in #10.

It seems that this should have been fixed by PR #14, but those changes cannot be found in release branch only in master. So maybe the fix is not released?

**Comment by shigupt202** [comment]
The release has been updated with the fix. @ronbeilinson and @anajavi Could you please confirm whether the action works for your scenario now?

**Comment by anajavi** [comment]
@shigupt202 the action works now. Thank you!

**Comment by ronbeilinson** [comment]
@shigupt202 will test and let you know! thanks for your help

**Comment by ronbeilinson** [comment]
works great, thank you!
