### ISSUE TITLE
Fix annotations links using github.com even for GHES

### ISSUE THREAD

**Issue by nv35** [Azure/k8s-deploy#201]
There are few locations were github.com is hardcoded, making it incompatible with github enterprise servers that are hosted on other domains.
From what I understood from these code lines, they are only cosmetic (sent as annotations in deployments).

https://github.com/Azure/k8s-deploy/blob/507f2d4fc713cdc92f96880e350464687ce2e960/src/utilities/workflowAnnotationUtils.ts#L24
https://github.com/Azure/k8s-deploy/blob/ca8d2604acf262265b6640fc4de4e060effbb555/src/utilities/githubUtils.ts#L47

There is `GITHUB_SERVER_URL` env var and [some others](https://docs.github.com/en/enterprise-server@2.22/actions/learn-github-actions/environment-variables) to get the server domain.

**Comment by OliverMKing** [comment]
Closed with #200 and action has been released. v4 (v4.1+) has this fix. Thanks!

**Comment by nv35** [comment]
@OliverMKing the pull request #200 that i've opened is about api calls sent to github.com. This issue is about cosmetic links shown to the user. I don't see any correction yet in the repo.
