### ISSUE TITLE
Any plan for supporting deployment using helm upgrade --install ?

### ISSUE THREAD

**Issue by s-tuli** [Azure/k8s-deploy#22]

**Comment by ds-ms** [comment]
Given that it can be achieved directly using CLI, I don't see any valid reason to incorporate it as an action. 

cc: @vithati @ammohant thoughts?

**Comment by vithati** [comment]
@s-tuli, helm task upgrade command support arguments. You can specify --install in arguments section.

**Comment by ds-ms** [comment]
@anraghun is there any plan to have a dedicated action for `helm-deploy` that you foresee in the near future?

**Comment by ds-ms** [comment]
Closing stale issue. feel free to reopen if this issue is still valid
