### ISSUE TITLE
The action input "images" not work

### ISSUE THREAD

**Issue by ray26** [Azure/k8s-deploy#23]
I hava use "images" option in the github workflow. The README said it will searched for in the image field of the input manifest files. For the matches found, the tags will be substituted. But when i use describe to check the version for the deploymeny, it shows that the deployment use the old version or the default version whic defined in the yaml in my repository. The correct version should be latest-da5602b7265634cef48c8749e2ed0b6494eb4e61, in workflow log it shows the correct version 
![image](https://user-images.githubusercontent.com/6435613/75250405-45639b00-5813-11ea-9539-965db8c27b32.png),but when i describe the pods it shows the 
![image](https://user-images.githubusercontent.com/6435613/75250490-704def00-5813-11ea-811a-2f7577ce76bc.png)

The manifest stays in:[https://github.com/wuhan-support/frontend/tree/dev/manifests]( )
The workflow logs in:[https://github.com/wuhan-support/frontend/runs/467145391?check_suite_focus=true]( )

I am not very sure wherther i have missed something in my config file?I have a guess if it is the error caused by the latest tag

Thanx for your help.

**Comment by ray26** [comment]
Excuse me, may I ask the process the issue. For that our program are using this for K8S auto deployment.

**Comment by ds-ms** [comment]
@ray26 try with `@v1` again.

**Comment by ds-ms** [comment]
Reopening this issue in reference to https://github.com/Azure/k8s-deploy/issues/26

**Comment by matthiasfalk** [comment]
I am still receiving this error.

part of workflow file:
`# Deploy app to AKS
    - name: Deploy to aks
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment.yaml
        images: |
          $CONTAINER_REGISTRY/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG
        imagepullsecrets: |
          dockerconfigjson-github-com`

part of deployment.yaml
'containers:
      - name: u8-sample-app
        image: docker.pkg.github.com/matthiasfalk/u8_sample_app/u8_sample_app:1
      imagePullSecrets:
        - name: dockerconfigjson-github-com'

Image tags do not get updated properly. Could you investigate please?

**Comment by ds-ms** [comment]
Does `$CONTAINER_REGISTRY/${{ github.repository }}/$IMAGE_NAME` translate to `docker.pkg.github.com/matthiasfalk/u8_sample_app/u8_sample_app`?

**Comment by matthiasfalk** [comment]
Hi @ds-ms: Yes, exactly. For me the uses: azure/k8s-deploy@v1.3 is not working.
I now tried it with a workaround to "manually" open the deployment.yaml with yt, update the tag and kubectl apply the edited deployment.yaml and it works.

**Comment by ds-ms** [comment]
@matthiasfalk `v1.3` is still in `Pre-release`. Is this issue happening for you in `v1.2` as well? 

cc: @ajinkya599

**Comment by matthiasfalk** [comment]
@ds-ms v1.2 is working now. I needed to use the convention `${{env.CONTAINER_REGISTRY}}/${{ github.repository }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}`. All other actions could handle the format `$CONTAINER_REGISTRY/${{ github.repository }}/$IMAGE_NAME:$IMAGE_TAG`. So I guess, I found the solution.
