### ISSUE TITLE
error: deployment exceeded its progress deadline

### ISSUE THREAD

**Issue by leandromsft** [Azure/k8s-deploy#234]
Hi folks,

I'm trying to deploy dotnet container application (backend and frontend) to AKS using blue/green strategy.

In the first run, everything works fine. (deploy and promote action)

In the second run the **deploy** action works fine but the **promote** action result in error.

```
 /usr/local/bin/kubectl rollout status Deployment/aspnetcorewebapp-deploy --insecure-skip-tls-verify
  Waiting for deployment "aspnetcorewebapp-deploy" rollout to finish: 1 out of 2 new replicas have been updated...
  error: deployment "aspnetcorewebapp-deploy" exceeded its progress deadline
  Error: Error: The process '/usr/local/bin/kubectl' failed with exit code 1
```

My workflows is configured as fellow:

```
     - name: Deploy to k8s
        uses: azure/k8s-deploy@v4
        with:
          manifests: my-app-artifact/kubernetes-containerapp.yaml
          imagepullsecrets: mysecret
          namespace: default
          strategy: blue-green
          action: deploy
          route-method: service
      
      - name: Promote App
        uses: azure/k8s-deploy@v4
        with:
          manifests: my-app-artifact/kubernetes-containerapp.yaml
          imagepullsecrets: mysecret
          namespace: default
          strategy: blue-green
          action: promote
          route-method: service
```

**Comment by jaiveerk** [comment]
Hey @leandromsft, would you mind doing the following and attaching the results to this thread:
- run `kubectl get pods` after the second run to identify which pod in your deployment is failing
- run `kubectl describe pods {PODNAME}` on the failing/crashed/erroring pod
- run `kubectl logs {PODNAME}`on the failing pod
- get the logs of the second run of your action from Github

Thanks!

**Comment by lsprado** [comment]
Hey @jaiveerk, thank you for help!

I found the problem this weekend 
The problem was that my node had no CPU available to create the new deployments. 
I increased the node machines, and the deployments worked.

This issue can be closed.

Thank you!

**Comment by jaiveerk** [comment]
thanks for letting us know!
