### ISSUE TITLE
Add support for an optional flag --force

### ISSUE THREAD

**Issue by s-tuli** [Azure/k8s-deploy#24]
Add support for an optional flag --force

Our team's (Azure dev Spaces) customer scenario requires us to deploy when a previous deployment already exists. It cannot be a clean deployment. And in this case, I get an error "file is immutable".

Please add it as an optional flag whose value is false by default. We will add a value true as part of our workflow.

**Additional Detail**: If a job has been created already, you cannot replace without using --force. 
One cannot replace jobs since Kubernetes adds labels on create. This is by design.
Specifically this error occurs for: https://github.com/Azure/dev-spaces/blob/master/samples/BikeSharingApp/PopulateDatabase/charts/populatedatabase/templates/job.yaml

Thanks!

**Comment by ds-ms** [comment]
@s-tuli Could you explain your scenario in detail, for building context in this thread.

**Comment by s-tuli** [comment]
> @s-tuli Could you explain your scenario in detail, for building context in this thread.

Added additional context above @ds-ms

**Comment by ds-ms** [comment]
@s-tuli I meant your use-case.

**Comment by ds-ms** [comment]
@tauhid621 to take a look
