### ISSUE TITLE
Feature Request: Switch to disable all annotations / labeling 

### ISSUE THREAD

**Issue by vitaly-pavluk** [Azure/k8s-deploy#242]
### Feature request

As a DevOps engineer working on the CI/CD GH workflow, I want to disable all annotations and labeling that 
`K8s-Deploy` GH action does, so they will not pollute K8s namespaces, deployments, pods, etc.
Now `K8s-Deploy` allows only disabling the namespace annotation but there is no way to disable pod labeling that does not work correctly.

Reason for turning off auto-annotations - I have a team-wide strategy for them so the GH action just pollutes K9s resources with labels and annotations that are not useful for my K8s resources.
NOTE: 
There is a bug in `K8s-Deploy` GH action that does not properly sanitize the workflow name before using it as in the POD/Service/Deployment label. 
E.g. my GitHub workflow name is "Build & Deploy Web Api" when `K8s-Deploy` calls kubectl to label all resources listed in the file it uses the following command 
`kubectl label -f /tmp/baked-template-12345.yaml workflowFriendlyName=Build_&_Deploy_Web_Api`
so the label `Build_&_Deploy_Web_Api` contains invalid symbol `&` that is not allowed by K8s
[Kubenetes - Label Syntax and character set](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)

**Comment by OliverMKing** [comment]
@vitaly-pavluk what version of this action are you running? v4.4 should remove the &.

**Comment by vitaly-pavluk** [comment]
@OliverMKing 
I've used version `azure/k8s-deploy@v3.1` per the first example I've seen on the GH 
[Basic deployment (without any deployment strategy)](https://github.com/Azure/k8s-deploy#basic-deployment-without-any-deployment-strategy)  
If  version 3.1 is not supported or has flaws so the examples should be updated accordingly to avoid confusion

**Comment by vitaly-pavluk** [comment]
Is it enough for the team to fix the issue?

**Comment by OliverMKing** [comment]
@vitaly-pavluk Have you tried v4 or v4.4? Those contain the fix.

The docs need to be updated to show v4 as the example.

**Comment by vitaly-pavluk** [comment]
@OliverMKing  No, I didn't try 4th version but changed the name of the workflow so it does not have unsupported chars. I explicitly mentioned v3 of the GH action as those that has an issue. If 3rd version is not supported anymore, please just close this issue and update docs to use only v4.4. 
Thank you.

**Comment by OliverMKing** [comment]
I have fixed the docs :).

**Comment by leemeichin** [comment]
Is there any chance of supporting this? I'm running `k8s-deploy` in a highly restricted workflow: it can only update deployments in a single namespace and has no access to anything else in the cluster (service account can only update deployments in a single namespace), neither does it know anything about docker.

The action completes successfully and prints a bunch of warnings at the annotation step, so it's not a huge deal, but it would be nice to omit the step entirely to avoid wasting time on CI.
