### ISSUE TITLE
Trying to specify different image version in workflow yaml than in deployment.yaml

### ISSUE THREAD

**Issue by sakthi-vetrivel** [Azure/k8s-deploy#3]
I'm running the azure-vote-front app with GitHub Actions and k8s-actions as a CI/CD pipeline with my AKS cluster. I want to have the k8s-deploy action to deploy the version of the image that I have just built using container-actions. However, I have a container image specified in the deployment 
,yaml that is a different version. Can I override this using the images field in k8s-deploy?

I'm mostly confused about what this means (from the README):

Artifact substitution
The deploy action takes as input a list of container images which can be specified along with their tags or digests. The same is substituted into the non-templatized version of manifest files before applying to the cluster to ensure that the right version of the image is pulled by the cluster nodes.

**Comment by sakthi-vetrivel** [comment]
Never mind, found some more documentation. Closing.

**Comment by SaiNageswarS** [comment]
Hi,

I'm facing the same problem. Could you please share the additional documentation.

Thanks
