### ISSUE TITLE
Bug: Validation error "Error: Error: undefined"

### ISSUE THREAD

**Issue by leaditnet** [Azure/k8s-deploy#308]
### What happened?

It  is not a bug
calling the get-credentials command from previous step will preserve the context and authorization
az aks get-credentials .....

I had this working before but today I get error , the testazure.yaml file is working fine from local machine using kubctl apply command 
But the github action is failing with this validation error I also don't know how to disable the validation on the action 

`error validating "/tmp/testazure.yaml": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false`

![image](https://github.com/Azure/k8s-deploy/assets/8202329/c51e8390-d6ae-41b1-be71-47d509eca6c5)

### Version

- [X] I am using the latest version

### Runner

Github Actions

### Relevant log output

`error validating "/tmp/testazure.yaml": error validating data: failed to download openapi: Get "http://localhost:8080/openapi/v2?timeout=32s": dial tcp [::1]:8080: connect: connection refused; if you choose to ignore these errors, turn validation off with --validate=false`
  Error: Error: undefined

**Comment by Duri9292** [comment]
Hello @pyramidsbuilder how did you resolve it? I'm facing the same issue ....

**Comment by mohoma** [comment]
@Duri9292 you should check your inputs (secrets) at the set-context step in your action.`k8s-url` & `k8s-secret`
