### ISSUE TITLE
Bug: deprecated NodeJs version

### ISSUE THREAD

**Issue by antonina-uglianets** [Azure/k8s-deploy#313]
### What happened?

In Github Actions I got the error using azure/k8s-deploy@v4 task.

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/k8s-deploy@v4.

Could you please update deprecated version?

### Version

- [X] I am using the latest version

### Runner

self-hosted

### Relevant log output

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/k8s-deploy@v4.

**Comment by davidgamero** [comment]
the v5.0.0 release is now out, and includes the node20 upgrade
