### ISSUE TITLE
Add ability to apply whole directories

### ISSUE THREAD

**Issue by dberzano** [Azure/k8s-deploy#34]
Same as:

```
kubectl apply -f my/dir/with/yaml/files/
```

Thanks!

**Comment by ds-ms** [comment]
cc: @anraghun 

I feel it's cleaner if we introduce a wild character like input where you supply something like `my/dir/with/yaml/files/*.yml` or something like that? Then it shouldn't restrict you from having other types of files in the folder

**Comment by ds-ms** [comment]
@anraghun any updates on the decision as to what we should go forward with?

**Comment by anraghun** [comment]
@ds-ms I like the approach you have proposed. We need to have a file based filter otherwise we would be mandating adding only manifest files to a particular folder. 
Let's proceed with `my/dir/with/yaml/files/*.yml`

**Comment by Enemico** [comment]
We also would really appreciate this feature.

**Comment by ds-ms** [comment]
@shigupt202 could you pick this up?

**Comment by shigupt202** [comment]
This feature can be accessed in v1.4 release of the action

**Comment by apgapg** [comment]
@shigupt202 Any sample docs on implementing this?
I don't see how can i implement above thing.
