### ISSUE TITLE
Need more explaination about the canary strategy

### ISSUE THREAD

**Issue by huangyingting** [Azure/k8s-deploy#40]
I tried create a new fresh github actions with deploy snippet like below

    - name: "Deploy azure vote front"
      uses: Azure/k8s-deploy@v1
      timeout-minutes: 5
      with:
        namespace: ${{env.NAMESPACE}}
        manifests: |
          manifests/front.yml
          manifests/service.yml
        images: |
          ${{secrets.REGISTRY_URL}}/${{env.IMAGE_NAME}}:${{ github.sha }}
        imagepullsecrets: |
          acr-secret
        strategy: canary
        percentage: 50

front.yml already set replica to 2, but the result I get from AKS cluster only shows on I have canary deployment, no baseline deployment
k get pod -n=github
NAME                                       READY   STATUS    RESTARTS   AGE
azure-vote-back-7d6d77f4ff-c8zf2           1/1     Running   0          48s
azure-vote-front-canary-7ffd6884cd-nnq7j   1/1     Running   0          39s

Is it an expected behavior?

**Comment by ds-ms** [comment]
@sundargs2000 given that you've been working on the strategies part recently.. could you address this question?

**Comment by sundargs2000** [comment]
@huangyingting if this is the first time you are deploying (ie. there are no azure-vote-front-* pods already), then you would only get '-canary' pods as there are no existing pods to make '-stable' pods to compare canary pods with. after you promote once and there are pods without any suffix, in the next run you would get both canary and stable pods.
