### ISSUE TITLE
Use github secrets in manifest files

### ISSUE THREAD

**Issue by niekappartmedia** [Azure/k8s-deploy#5]
Currently i am setting up k8s deployment of my containers via the k8s-deploy action.
Huge thnx for creating this by the way.
But for now i am having troubles with using github secrets in the manifest yaml files.
I am trying to setup a mysql database container for example and want to set the username and password with my Github secrets. But in the manifest yaml files i cant use the github secrets.

Is this possible or is there an other way to achieve this?

Thanx for your help.

**Comment by shashankbarsin** [comment]
There's another [action](https://github.com/Azure/k8s-create-secret) for creating a generic secret or docker-registry secret. Use the k8s-create-secret to create the secret with some name you provide as input. Later reference that secret in your manifest files and use this action to deploy the manifests.
