### ISSUE TITLE
[Blue-Green Bug Bash] Promote SMI deletes workloads first and then the TrafficSplit

### ISSUE THREAD

**Issue by ajinkya599** [Azure/k8s-deploy#59]
Repro steps:
- Deploy with `route-method` as `smi`
- Promote the deployment

Current behaviour:
- Deployment and temporary services are deleted first, and then the TrafficSplit resource is deleted
![image](https://user-images.githubusercontent.com/11447401/93493042-1cc6fe00-f929-11ea-8e47-1ccc0f03a981.png)

Expected behaviour:
- TrafficSplit should be deleted first. Otherwise, during the transition, there would be broken references of services in TrafficSplit

**Comment by ajinkya599** [comment]
The same is applicable for `reject` case.

**Comment by shigupt202** [comment]
Are we seeing any unwanted behaviour because of this currently?

**Comment by ajinkya599** [comment]
Upon investigating further, I realised it should be:
- Configure TrafficSplit
- Delete Green deployment
- Delete TrafficSplit
- Delete temporary services

@shigupt202 This can potentially cause a glitch - Requests failing because the services that TrafficSplit is referring are deleted.
Let's discuss this once.
