### ISSUE TITLE
Deploying with latest tag?

### ISSUE THREAD

**Issue by alexpapworth** [Azure/k8s-deploy#85]
Hiya.

I've got my Kubernetes config set up so it just uses the latest Docker image each time. I've found that this means running `kubectl apply -f deployment.yml` doesn't do anything, I'm assuming because Kubernetes can't recognise that there's a new image for it to deploy.

So instead, I've been running the `kubectl rollout restart deployment/my-app` command.

It seems that this Action uses the `apply` approach. Is there a way I can still use this Action while also only ever pushing my `latest` image to the Docker registry?

**Comment by ds-ms** [comment]
You could change your imagePullPolcy to make it work. 
Here's some documentation I found: https://kubernetes.io/docs/concepts/containers/images/#updating-images

**Comment by alexpapworth** [comment]
Ah, nice. I see. So the `latest` tag deploy instructions need to be added to the Kubernetes config, rather than the Github Action config. Nice!

**Comment by flurreN** [comment]
Even with `imagePullPolicy: Always` I still have to do `kubectl rollout restart deployment/my-app` for it to actually re-deploy with the new image.

I tried looking into the different strategies, but I couldn't get it to work the way I want.

@ds-ms could you point me in the right direction if I just want it to redeploy the pod with the new image.

**Comment by sam-h-bean** [comment]
I don't think it's gonna work
