### ISSUE TITLE
Parsing of image substitution incomplete

### ISSUE THREAD

**Issue by SamMousa** [Azure/k8s-deploy#86]
This is related to #23 in the sense that the symptom is that replacements don't work.

The regex used to parse an image identifier in the yaml is `const imageKeyword = line.match(/^ *image:/);`.
I had an issue where it was not working for me, because I had a config like this:
```yaml
..
  containers:
    - image: test
      name: test
```

Which isn't correctly parsed by the regex.

The clean solution would be to use a real yaml parser, but an ugly quick fix could be to allow for this case.

If you want to have the quick fix I can make a PR, just let me know.
The correct regex is: `/^ *(?:- )?image:/`

**Comment by ds-ms** [comment]
That's a good catch. @SamMousa would you be willing to raise a fix for the same?

**Comment by SamMousa** [comment]
Do you want the quick fix? Because that I can do.

I'm not  not able to commit the time to implement the use of a proper yaml parser that just inspects the names of object properties...

**Comment by ds-ms** [comment]
You need to update the `.ts` files then locally run `npm run-script build`. I agree it's a little redundant, but this way we get to validate the unexpected compile changes too; which we can confidently take to our releases branch. 

The quick fix should do. 

cc: @shigupt202 could you validate how we missed this? I remember we solved this in the ADO task?

**Comment by SamMousa** [comment]
>  I agree it's a little redundant, but this way we get to validate the unexpected compile changes too

I think it's actually a risk, see #87.

I'll create a PR for the changed regex this week.

**Comment by ds-ms** [comment]
Cool. Tag @shigupt202 in your PR so he can take it forward. :)

**Comment by shigupt202** [comment]
> You need to update the `.ts` files then locally run `npm run-script build`. I agree it's a little redundant, but this way we get to validate the unexpected compile changes too; which we can confidently take to our releases branch.
> 
> The quick fix should do.
> 
> cc: @shigupt202 could you validate how we missed this? I remember we solved this in the ADO task?

@ds-ms I can see the fix in ADO task was done in this [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/11883). 
Also, in this task we are using yaml parser for `updateImagePullSecretsInManifestFiles`. But somehow the change was missed for `updateContainerImagesInManifestFiles`.

**Comment by SamMousa** [comment]
Since this is something you guys have worked on internally; I'll refrain from making a PR for now and let you resolve this for yourselves :)
