### ISSUE TITLE
Split source and compiled files

### ISSUE THREAD

**Issue by SamMousa** [Azure/k8s-deploy#87]
While there could be arguments for having both the source TS and the compiled JS files in the same repository, I do not believe that there are arguments for having them in PRs / manual commits.

I suspect that code reviews will mostly focus on the TS part which means manual changes to the JS could sneak past reviewers which is a security concern. Furthermore I cannot imagine any sane person enjoys comparing TS and JS code just to see if they do the same thing..

If we need to have both in the same repo, the least we could do is have CI compile the files and commit them back every time a change is made to the TS files. This also guarantees that a uniform compiler configuration is used.

Just to be clear: I don't believe there is a good argument to have the JS files in this repo at all, they could either be compiled when the action runs or be compiled just for the tagged commit and added as a release artifact. I'm not sure how Github Actions uses the release though, so someone with a bit more expertise should look at that first.

**Comment by ds-ms** [comment]
We have to check in our `node_modules` as well as the `.js` files to make any action work. You could checkout this branch:https://github.com/Azure/k8s-deploy/tree/releases/v1.4 

I do agree with your points. Also, we are currently in the process of standardising the way we maintain our actions right now. This seems like a good addition to the bunch of new standards we're planning for all of our azure actions. 😄 

Looping in @N-Usha to take a look.

**Comment by SamMousa** [comment]
https://github.com/actions/typescript-action

I think the recommendation is to use a different branch for releases.

**Comment by ds-ms** [comment]
@SamMousa I don't think there are any apprehensions from the action team to not have `.js` files in your main branch either. Some actions could have their tests run on the `.js` alone.

I agree that they're redundant in our case as jest test runs work against `.ts` files. We will consider removing them.

**Comment by SamMousa** [comment]
I think they are a security risk unless you check everything every time... If I add a dependency, are you checking to see if I didn't change the dependency code during review?

The review load is bigger. An alternative I've used is to at least have a CI job for compilation and dep installation to see if it gets the same result. Than you can remove the risk and burden of manual review. Of course that requires the compilation to be deterministic..
